### ISSUE TITLE
Publish schedule?

### ISSUE THREAD

**Issue by ToniKorin** [MobileChromeApps/cordova-plugin-push#1]
Hi Idan,

I was looking the plugins for the iOS silent notification and your work seems to be very promising. Any plans to publish the plugin at http://plugins.cordova.io/ ?

Cheers,
 Toni

**Comment by imintz** [comment]
The current plan is to publish the plugin on npm in the near future. Thanks for your interest.

**Comment by imintz** [comment]
The plugin has been published npm and you can find it [here](https://www.npmjs.com/package/cordova-plugin-push).
